services:
  web:
    build: .
    container_name: banco-marcas-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads
      - /var/lib/banco-de-marcas/uploads:/var/lib/banco-de-marcas/uploads

